name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]

    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Build with Gradle
      run: ./gradlew publishToMavenLocal
      env:
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.signingKey }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.signingPassword }}
    - name: Upload library
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-library
        path: ~/.m2

  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [28, 29, 30, 31]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          script: ./gradlew connectedCheck
